FROM apache/airflow:2.5.1-python3.10
USER root


# Copy requirements.txt file into the image root directory
COPY requirements.txt /

# Update package repository and install additional tools
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
  && apt-get install nano \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Switch back to the 'airflow' user
USER airflow

# Install Python packages listed in requirements.txt using pip
RUN pip install --no-cache-dir -r /requirements.txt


